version: '3.8'
services:

  tbng-bridge:
    extends:
      file: tbng-bridge.yaml
      service: tbng-bridge

  tbng-3proxy:
    extends:
      file: tbng-3proxy.yaml
      service: tbng-3proxy
    links:
      - tbng-bridge:tor
    depends_on:
      tbng-bridge:
        condition: service_healthy

include:
  - volumes.yaml
