version: '3.8'
#### One should disable unused services
services:
## Comment tpws service if not used
#  tbng-tpws:
#    extends: 
#      file: tbng-tpws.yaml
#      service: tbng-tpws
###  override env here -- look for values from environment section of tbng-tpws.yaml AND from entrypoint.sh. Defaults are for youtube@Russia 
#   environment:

## Comment nfqws service if not used
#  tbng-nfqws:
#    extends:
#      file: tbng-nfqws.yaml
#      service: tbng-nfqws
###  override env here  -- look for values from environment section of tbng-nfqws.yaml AND from entrypoint.sh. Defaults are for youtube@Russia
#   environment:
###
  tbng-tor:
    extends:
      file: tbng-tor.yaml
      service: tbng-tor

  tbng-privoxy:
    extends:
      file: tbng-privoxy.yaml
      service: tbng-privoxy
    depends_on:
      tbng-tor:
        condition: service_healthy

## Comment i2p service if not used.
#  tbng-i2p:
#    extends:
#      file: tbng-i2p.yaml
#      service: tbng-i2p

  tbng-ap:
    extends:
      file: tbng-ap.yaml
      service: tbng-ap
###  override env here  -- look for values from environment section of tbng-ap.yaml. NO Defaults. Settings are mandatory
#   environment:

include:
  - volumes.yaml

