version: '3.8'

services:
## This part is mutual exclusive with tor+privoxy
#  tbng-tpws:
#    extends: tbng-tpws.yaml
#    service: tbng-tpws
###
  tbng-tor:
    extends:
      file: tbng-tor.yaml
      service: tbng-tor

  tbng-privoxy:
    extends:
      file: tbng-privoxy.yaml
      service: tbng-privoxy
    depends_on:
      tbng-tor:
        condition: service_healthy

## Remove i2p service if not used.
  tbng-i2p:
    extends:
      file: tbng-i2p.yaml
      service: tbng-i2p

  tbng-ap:
    extends:
      file: tbng-ap.yaml
      service: tbng-ap
#    environment:
#     Override env here

include:
  - volumes.yaml

