version: '3.8'
services:

  tbng-tor:
    image: tbng-tor
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "--fail", "--socks5", "127.0.0.1:9050","https://torproject.org"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
     - torconf:/opt/torconf
     - tordata:/var/lib/tor
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 64m

  tbng-privoxy:
    image: tbng-privoxy
    restart: unless-stopped
    network_mode: host
    depends_on:
      tbng-tor:
        condition: service_healthy
    volumes:
     - privoxyconf:/opt/privoxyconf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 16m

## Remove i2p service if not used.
  tbng-i2p:
    image: tbng-i2p
    restart: unless-stopped
    network_mode: host
    stop_grace_period: 40s
    volumes:
     - i2pconf:/home/i2p-tbng/.i2p
     - i2psnark:/home/i2p-tbng/i2psnarkdata
     - i2pdata:/home/i2p-tbng/i2p
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 320m
     
  tbng-ap:
    image: tbng-ap
    restart: unless-stopped
    network_mode: host
    cap_add:
     - NET_ADMIN
     - SYS_ADMIN
   ###  Remove "devices" section if you are not using /dev/rfkill (e.g. not passed to LXC container).
    devices:
     - "/dev/rfkill:/dev/rfkill"
    environment:
   ### out and in interfaces
     - LAN=wlan0
     - WAN=eth0
   ### initial dns -- switch to your own if initial is blocked
     - DNS_SERVERS=8.8.8.8, 8.8.4.4
   ### subnet for AP
     - SUBNET=192.168.242.0
     - AP_ADDR=192.168.242.1
   ### hostapd-related
     - SSID=MyDockerAP
     - CHANNEL=11
     - WPA_PASSPHRASE=topsecretpassword
     - HW_MODE=g
     - DRIVER=nl80211
     - HT_CAPAB=[HT40-][SHORT-GI-20][SHORT-GI-40]
     - MODE=host
    ### Allowed ports -- e.g. 8118 will allow to setup a proxy
     - ALLOWED_PORTS_TCP=8118 9050 7657 22
     - ALLOWED_PORTS_UDP=9053 53
    ### can be direct|tor|privoxy
     - TOR_MODE=privoxy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64m

volumes:
  torconf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/conf/tbng-tor"
  tordata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/data/tbng-tor"
  privoxyconf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/conf/tbng-privoxy"
  i2pconf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/conf/tbng-i2p"
  i2psnark:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/data/i2psnark"
  i2pdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/data/tbng-i2p"

