version: '3.8'
services:

  tbng-tpws:
    image: tbng-tpws
    restart: unless-stopped
    container_name: tbng-tpws
    network_mode: host
    environment:
      HOST_LIST: >
        googlevideo.com
      INTERFACE: wlan0
      DEBUG_LEVEL: 1
      SETTINGS: "--disorder --tlsrec=sni --split-pos=2"

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 16m


