version: '3.8'
services:
  tbng-ap:
    image: tbng-ap
    container_name: tbng-ap
    restart: unless-stopped
    network_mode: host
    cap_add:
     - NET_ADMIN
     - SYS_ADMIN
   ###  Remove "devices" section if you are not using /dev/rfkill (e.g. not passed to LXC container).
    devices:
     - "/dev/rfkill:/dev/rfkill"
    environment:
   ### out and in interfaces
     - LAN=wlan0
     - WAN=eth0
   ### initial dns -- switch to your own if initial is blocked
     - DNS_SERVERS=8.8.8.8, 8.8.4.4
   ### subnet for AP
     - SUBNET=192.168.242.0
     - AP_ADDR=192.168.242.1
   ### hostapd-related
     - SSID=MyDockerAP
   #  - CHANNEL=11 #Set explicit channel number for 2.4Ghz
     - CHANNEL=161
     - COUNTRY_COODE=RU
     - WPA_PASSPHRASE=topsecretpassword
    # - HW_MODE=g  #Set this for 2.4Ghz
     - HW_MODE=a
    ### Allowed ports -- e.g. 8118 will allow to setup a proxy
     - ALLOWED_PORTS_TCP=8118 9050 7657 22
     - ALLOWED_PORTS_UDP=9053 53
    ### can be direct|tor|privoxy
     - TOR_MODE=privoxy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64m

