version: '3.8'
services:

  tbng-tpws:
    image: tbng-tpws
    restart: unless-stopped
    container_name: tbng-tpws
    network_mode: host
    environment:
      HOST_LIST: >
        googlevideo.com
        ggpht.com
        ytimg.com
        l.google.com
        youtube.com
        play.google.com
        youtubei.googleapis.com
        youtu.be
        nhacmp3youtube.com
        googleusercontent.com
      INTERFACE: wlan0
      DEBUG_LEVEL: 1

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 16m


